services:
  - type: web
    name: ngocanh-tuuyen
    env: node
    plan: free
    region: singapore
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
